server:  
  port: 9002
  
spring:
  data:
     rest:
       basePath: /api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://pennstack-mysql-docker-container:3306/spring_app_db?useSSL=FALSE&allowPublicKeyRetrieval=true
    url: jdbc:mysql://172.23.11.113:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true 

    username: rootuser
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type: debug
        
        